rules:
  incomplete_attachment:
    condition:
      - or:
          - regex: '<!-- Uploading .*? -->'
          - regex: '<!-- Failed to upload .*? -->'
    action:
      comment:
        message:
          '@{{ comment.author }} seems you have a incomplete upload. Please
          check.'
      label:
        add: 'more info needed'
      assign:
        add: ngc7331

  resolve:
    condition:
      - regex: "^\/resolve"
      - state: open
      - event_type: issue_comment
    action:
      label:
        remove: 'more info needed'
      state:
        reason: completed

  unresolve:
    condition:
      - regex: "^\/unresolve"
      - state: closed
      - event_type: issue_comment
    action:
      label:
        add: 're-opened'
      state:
        reason: reopened

  hello:
    condition:
      - regex: "^\/hello"
      - event_type: issue_comment
    action:
      comment:
        message: 'Hello @{{ comment.author }}!'
      dispatch:
        workflow: ci-test-dispatch.yml
        inputs:
          author: '{{ comment.author }}'

global:
  - regex_title: '[TEST]'
  - member: only
