name: Issue Bot CI Test
on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Run issue bot
        uses: ngc7331/actions-issue-bot@v1
        with:
          config: .github/issue-bot-test.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
